config/routes.rb
Rails.application.routes.draw do
  resources :memberships

  resources :beer_clubs

  resources :users

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :users do
    post 'freeze_user', on: :member
  end

  resource :session, only: [:new, :create]

  resources :beers

  resources :styles

  resources :breweries

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :ratings, only: [:index, :new, :create, :destroy]

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  root 'breweries#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingMethods

  scope :admin, -> { where admin:true }
  scope :regular, -> { where admin:[nil,false] }

  scope :account_frozen, -> { where account_frozen:true}
  scope :active, -> { where account_frozen:[nil,false] }

  has_secure_password

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  validates :username, uniqueness: true,
                       length: { in: 3..15 }

  validates :password, length: { minimum: 4 }

  validates :password, format: { with: /\d.*[A-Z]|[A-Z].*\d/,  message: "has to contain one number and one upper case letter" }

  def favorite_beer
    return nil if ratings.empty?   # palautetaan nil jos reittauksia ei ole
    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_style
    return nil if ratings.empty?
    rated_styles={}
    #enumerate with same style ratings chunked together:
    ratings.includes(:beer).order("Beers.style_id").chunk{ |rating| rating.beer.style}.each {
        |style, ratings|
        rated_styles[style]=average_rating_from ratings}
    rated_styles.max[0]   #max gives the [style, average] array with the highest average
  end

  def favorite_brewery
    return nil if ratings.empty?
    rated_breweries={}
    #enumerate with same brewery ratings chunked together:
    ratings.includes(:beer).order("Beers.brewery_id").chunk{ |rating| rating.beer.brewery}.each {
        |brewery, ratings|
      rated_breweries[brewery]=average_rating_from ratings}
    rated_breweries.max[0]   #max gives the [brewery, average] array with the highest average
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :freeze_user]
  before_action :ensure_that_admin, only: [:destroy, :freeze_user]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users/1/freeze_user
  def freeze_user
    @user.update_attribute :account_frozen, (not @user.account_frozen)

    new_status = @user.account_frozen? ? "frozen" : "not frozen"

    redirect_to :back, notice:"user #{@user.username} account is now #{new_status}"
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if current_user == @user
      @user.destroy
      session[:user_id] = nil
    end
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="1"></th>
      <th></th>
      <% if current_user.admin %>
      <th></th>
          <% end %>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
            <% if user.admin %>
                <td><span class="label label-info"> administrator</span></td>
                <% end %>
        <% if current_user.admin %>
        <% if user.account_frozen  %>
            <td><span class="label label-info">account frozen</span></td>
        <% end %>
            <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class:"btn btn-primary" %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @user.username %>
</h2>

<% if @user.beer_clubs.any? %>
    member of
    <% @user.beer_clubs.each do |club| %>
        <%= link_to club.name, club %>
    <% end %>
<% end %>

<% if @user.ratings.empty? %>
  <p>has not yet rated any beers</p>
<% else %>
  <p>
    Has made <%= pluralize(@user.ratings.count, 'rating') %>, average <%= round @user.average_rating %>.
    Favorite style is <%= @user.favorite_style.name %>.
    Favorite brewery is <%= @user.favorite_brewery.name %>.
  </p>
<% end %>
<ul>
  <% @user.ratings.each do |rating| %>
    <li>
      <%= rating %>
      <% if @user == current_user %>
        <%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if @user == current_user %>
  <%= link_to 'Change password', edit_user_path(@user), class:"btn btn-primary" %>
  <%= link_to 'Delete account', @user, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></
<% end %>

<% if current_user.admin == true %>
    <%= link_to 'Freeze/defreeze account', freeze_user_user_path(@user), method: :post, class:"btn btn-danger" %>
<% end %>